name: Build Thumbnails

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Puppeteer
        run: npm install puppeteer

      - name: Make output directory
        run: mkdir -p thumbs

      - name: Generate thumbnails
        run: node .github/thumbs/snap.js

      - name: Commit thumbnails
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add thumbs
          git commit -m "Add/update thumbnails" || echo "No changes to commit"
          git push
